import numpy as np
import pandas as pd

# You can also use this section to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')

URL="https://web.archive.org/web/20230902185326/https://en.wikipedia.org/wiki/List_of_countries_by_GDP_%28nominal%29"
tables = pd.read_html(URL)
df = tables[3]
df.columns = range(df.shape[1])
goodcols=df[[0,2]]
top = goodcols[0:11]

top.columns =["Country","GDP (Millions USD)"]

top['GDP (Millions USD)'] = top['GDP (Millions USD)'].astype(int)
top['GDP (Millions USD)'] = top[['GDP (Millions USD)']] / 1000
top['GDP (Millions USD)'] = top['GDP (Millions USD)'].round(2)

top.columns =["Country","GDP (Billions USD)"]

top.to_csv("data.csv")

print(top)
