version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5000"
      - "3000:3000"  # Expose the LiveReload server on port 3000
    volumes:
      - ./src:/app
    environment:
      - FLASK_ENV=development
